//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExponentialFailureRateLimiter) DeepCopyInto(out *ExponentialFailureRateLimiter) {
	*out = *in
	if in.MaxDelay != nil {
		in, out := &in.MaxDelay, &out.MaxDelay
		*out = new(v1.Duration)
		**out = **in
	}
	if in.BaseDelay != nil {
		in, out := &in.BaseDelay, &out.BaseDelay
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExponentialFailureRateLimiter.
func (in *ExponentialFailureRateLimiter) DeepCopy() *ExponentialFailureRateLimiter {
	if in == nil {
		return nil
	}
	out := new(ExponentialFailureRateLimiter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReconciliationPolicy) DeepCopyInto(out *ReconciliationPolicy) {
	*out = *in
	if in.ExponentialFailureRateLimiter != nil {
		in, out := &in.ExponentialFailureRateLimiter, &out.ExponentialFailureRateLimiter
		*out = new(ExponentialFailureRateLimiter)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReconciliationPolicy.
func (in *ReconciliationPolicy) DeepCopy() *ReconciliationPolicy {
	if in == nil {
		return nil
	}
	out := new(ReconciliationPolicy)
	in.DeepCopyInto(out)
	return out
}
