/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package pipeline

import (
	"go/types"
	"os"
	"path/filepath"
	"strings"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	twtypes "github.com/muvaf/typewriter/pkg/types"
	"github.com/muvaf/typewriter/pkg/wrapper"
	"github.com/pkg/errors"

	"github.com/crossplane-contrib/terrajet/pkg/pipeline/templates"
	tjtypes "github.com/crossplane-contrib/terrajet/pkg/types"
)

// GenStatement is printed on every generated file.
const GenStatement = "// Code generated by terrajet. DO NOT EDIT."

// NewCRDGenerator returns a new CRDGenerator.
func NewCRDGenerator(groupDir, rootModulePath, group string) *CRDGenerator {
	return &CRDGenerator{
		GroupDir:       groupDir,
		RootModulePath: rootModulePath,
		Group:          group,
	}
}

// CRDGenerator takes certain information referencing Terraform resource definition
// and writes kubebuilder CRD file.
type CRDGenerator struct {
	GroupDir       string
	RootModulePath string
	Group          string
}

// Generate builds and writes a new CRD out of Terraform resource definition.
func (cg *CRDGenerator) Generate(version, kind string, schema *schema.Resource) error {
	groupPkgPath := filepath.Join(cg.RootModulePath, "apis", strings.ToLower(strings.Split(cg.Group, ".")[0]), strings.ToLower(version))
	kindPkgPath := filepath.Join(groupPkgPath, strings.ToLower(kind))
	// TODO(muvaf): Loading the local package will result in error if there is
	// any compilation errors, which is the case before running kubebuilder
	// generators. For now, we act like the target package is empty.
	pkg := types.NewPackage(kindPkgPath, strings.ToLower(version))
	file := wrapper.NewFile(pkg.Path(), pkg.Name(), templates.CRDTypesTemplate,
		wrapper.WithGenStatement(GenStatement),
		wrapper.WithHeaderPath("hack/boilerplate.go.txt"), // todo
	)
	typeList, err := tjtypes.NewBuilder(pkg).Build(kind, schema)
	if err != nil {
		return errors.Wrapf(err, "cannot build types for %s", kind)
	}
	typePrinter := twtypes.NewTypePrinter(file.Imports, pkg.Scope())
	typesStr, err := typePrinter.Print(typeList)
	if err != nil {
		return errors.Wrap(err, "cannot print the type list")
	}
	vars := map[string]interface{}{
		"Types": typesStr,
		"CRD": map[string]string{
			"APIVersion": version,
			"Group":      cg.Group,
			"Kind":       kind,
		},
		"VersionPackageAlias": file.Imports.UsePackage(groupPkgPath),
	}
	filePath := filepath.Join(cg.GroupDir, strings.ToLower(version), strings.ToLower(kind), "zz_types.go")
	return errors.Wrap(file.Write(filePath, vars, os.ModePerm), "cannot write crd file")
}
