// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: diff/v1alpha1/diff.proto

// This package defines the provider diff protocol & the associated gRPC services.

//buf:lint:ignore PACKAGE_DIRECTORY_MATCH

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlanRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The desired managed resource, as full JSON (apiVersion, kind, metadata,
	// spec). Always set; the protocol does not express deletion (see below).
	DesiredResource *structpb.Struct `protobuf:"bytes,1,opt,name=desired_resource,json=desiredResource,proto3" json:"desired_resource,omitempty"`
	// The live resource, with status.atProvider populated. Must carry the
	// same apiVersion as the desired resource. Unset for a resource that
	// does not exist yet, which plans as a create.
	LiveResource *structpb.Struct `protobuf:"bytes,2,opt,name=live_resource,json=liveResource,proto3" json:"live_resource,omitempty"`
	// The Kubernetes object store that will be used to initialize an
	// in-memory Kubernetes API client.
	KubernetesObjectStore []*structpb.Struct `protobuf:"bytes,3,rep,name=kubernetes_object_store,json=kubernetesObjectStore,proto3" json:"kubernetes_object_store,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PlanRequest) Reset() {
	*x = PlanRequest{}
	mi := &file_diff_v1alpha1_diff_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanRequest) ProtoMessage() {}

func (x *PlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diff_v1alpha1_diff_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanRequest.ProtoReflect.Descriptor instead.
func (*PlanRequest) Descriptor() ([]byte, []int) {
	return file_diff_v1alpha1_diff_proto_rawDescGZIP(), []int{0}
}

func (x *PlanRequest) GetDesiredResource() *structpb.Struct {
	if x != nil {
		return x.DesiredResource
	}
	return nil
}

func (x *PlanRequest) GetLiveResource() *structpb.Struct {
	if x != nil {
		return x.LiveResource
	}
	return nil
}

func (x *PlanRequest) GetKubernetesObjectStore() []*structpb.Struct {
	if x != nil {
		return x.KubernetesObjectStore
	}
	return nil
}

type PlanResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Action          string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"` // no-op | create | update | replace
	Changes         []*FieldChange         `protobuf:"bytes,2,rep,name=changes,proto3" json:"changes,omitempty"`
	RequiresReplace bool                   `protobuf:"varint,3,opt,name=requires_replace,json=requiresReplace,proto3" json:"requires_replace,omitempty"`
	ReplaceFields   []string               `protobuf:"bytes,4,rep,name=replace_fields,json=replaceFields,proto3" json:"replace_fields,omitempty"` // CRD paths, e.g. spec.forProvider.region
	// repeated Diagnostic diagnostics = 5;
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	ComputedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=computed_at,json=computedAt,proto3" json:"computed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanResponse) Reset() {
	*x = PlanResponse{}
	mi := &file_diff_v1alpha1_diff_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanResponse) ProtoMessage() {}

func (x *PlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diff_v1alpha1_diff_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanResponse.ProtoReflect.Descriptor instead.
func (*PlanResponse) Descriptor() ([]byte, []int) {
	return file_diff_v1alpha1_diff_proto_rawDescGZIP(), []int{1}
}

func (x *PlanResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PlanResponse) GetChanges() []*FieldChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *PlanResponse) GetRequiresReplace() bool {
	if x != nil {
		return x.RequiresReplace
	}
	return false
}

func (x *PlanResponse) GetReplaceFields() []string {
	if x != nil {
		return x.ReplaceFields
	}
	return nil
}

func (x *PlanResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PlanResponse) GetComputedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ComputedAt
	}
	return nil
}

type FieldChange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CRD path in the schema of the request's apiVersion,
	// e.g. spec.forProvider.deletionWindowInDays.
	Field           string      `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Current         *FieldValue `protobuf:"bytes,2,opt,name=current,proto3" json:"current,omitempty"` // Unset when the field does not exist yet.
	Desired         *FieldValue `protobuf:"bytes,3,opt,name=desired,proto3" json:"desired,omitempty"` // Unset when the change removes the field.
	RequiresReplace bool        `protobuf:"varint,4,opt,name=requires_replace,json=requiresReplace,proto3" json:"requires_replace,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FieldChange) Reset() {
	*x = FieldChange{}
	mi := &file_diff_v1alpha1_diff_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldChange) ProtoMessage() {}

func (x *FieldChange) ProtoReflect() protoreflect.Message {
	mi := &file_diff_v1alpha1_diff_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldChange.ProtoReflect.Descriptor instead.
func (*FieldChange) Descriptor() ([]byte, []int) {
	return file_diff_v1alpha1_diff_proto_rawDescGZIP(), []int{2}
}

func (x *FieldChange) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *FieldChange) GetCurrent() *FieldValue {
	if x != nil {
		return x.Current
	}
	return nil
}

func (x *FieldChange) GetDesired() *FieldValue {
	if x != nil {
		return x.Desired
	}
	return nil
}

func (x *FieldChange) GetRequiresReplace() bool {
	if x != nil {
		return x.RequiresReplace
	}
	return false
}

// The value on one side of a change. Unset, concrete (including explicit
// null), unknown, sensitive, and unresolved are five distinct states.
type FieldValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*FieldValue_Value
	//	*FieldValue_Unknown
	//	*FieldValue_Sensitive
	//	*FieldValue_Unresolved
	Kind          isFieldValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldValue) Reset() {
	*x = FieldValue{}
	mi := &file_diff_v1alpha1_diff_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldValue) ProtoMessage() {}

func (x *FieldValue) ProtoReflect() protoreflect.Message {
	mi := &file_diff_v1alpha1_diff_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldValue.ProtoReflect.Descriptor instead.
func (*FieldValue) Descriptor() ([]byte, []int) {
	return file_diff_v1alpha1_diff_proto_rawDescGZIP(), []int{3}
}

func (x *FieldValue) GetKind() isFieldValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *FieldValue) GetValue() *structpb.Value {
	if x != nil {
		if x, ok := x.Kind.(*FieldValue_Value); ok {
			return x.Value
		}
	}
	return nil
}

func (x *FieldValue) GetUnknown() bool {
	if x != nil {
		if x, ok := x.Kind.(*FieldValue_Unknown); ok {
			return x.Unknown
		}
	}
	return false
}

func (x *FieldValue) GetSensitive() bool {
	if x != nil {
		if x, ok := x.Kind.(*FieldValue_Sensitive); ok {
			return x.Sensitive
		}
	}
	return false
}

func (x *FieldValue) GetUnresolved() bool {
	if x != nil {
		if x, ok := x.Kind.(*FieldValue_Unresolved); ok {
			return x.Unresolved
		}
	}
	return false
}

type isFieldValue_Kind interface {
	isFieldValue_Kind()
}

type FieldValue_Value struct {
	// The concrete value. google.protobuf.Value carries strings, numbers,
	// booleans, lists, objects, and explicit nulls, so null and "" differ.
	Value *structpb.Value `protobuf:"bytes,1,opt,name=value,proto3,oneof"`
}

type FieldValue_Unknown struct {
	// The value is known only after apply.
	Unknown bool `protobuf:"varint,2,opt,name=unknown,proto3,oneof"`
}

type FieldValue_Sensitive struct {
	// The value is sensitive and was redacted by the server.
	Sensitive bool `protobuf:"varint,3,opt,name=sensitive,proto3,oneof"`
}

type FieldValue_Unresolved struct {
	// The value comes from a reference (a Secret, or another resource via
	// a ref field) the server cannot resolve, so this plan could not
	// evaluate it. The reconciler will resolve it and may find a real
	// change here.
	Unresolved bool `protobuf:"varint,4,opt,name=unresolved,proto3,oneof"`
}

func (*FieldValue_Value) isFieldValue_Kind() {}

func (*FieldValue_Unknown) isFieldValue_Kind() {}

func (*FieldValue_Sensitive) isFieldValue_Kind() {}

func (*FieldValue_Unresolved) isFieldValue_Kind() {}

var File_diff_v1alpha1_diff_proto protoreflect.FileDescriptor

const file_diff_v1alpha1_diff_proto_rawDesc = "" +
	"\n" +
	"\x18diff/v1alpha1/diff.proto\x12\x13upjet.diff.v1alpha1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe0\x01\n" +
	"\vPlanRequest\x12B\n" +
	"\x10desired_resource\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x0fdesiredResource\x12<\n" +
	"\rlive_resource\x18\x02 \x01(\v2\x17.google.protobuf.StructR\fliveResource\x12O\n" +
	"\x17kubernetes_object_store\x18\x03 \x03(\v2\x17.google.protobuf.StructR\x15kubernetesObjectStore\"\x87\x02\n" +
	"\fPlanResponse\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12:\n" +
	"\achanges\x18\x02 \x03(\v2 .upjet.diff.v1alpha1.FieldChangeR\achanges\x12)\n" +
	"\x10requires_replace\x18\x03 \x01(\bR\x0frequiresReplace\x12%\n" +
	"\x0ereplace_fields\x18\x04 \x03(\tR\rreplaceFields\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12;\n" +
	"\vcomputed_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"computedAt\"\xc4\x01\n" +
	"\vFieldChange\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x129\n" +
	"\acurrent\x18\x02 \x01(\v2\x1f.upjet.diff.v1alpha1.FieldValueR\acurrent\x129\n" +
	"\adesired\x18\x03 \x01(\v2\x1f.upjet.diff.v1alpha1.FieldValueR\adesired\x12)\n" +
	"\x10requires_replace\x18\x04 \x01(\bR\x0frequiresReplace\"\xa2\x01\n" +
	"\n" +
	"FieldValue\x12.\n" +
	"\x05value\x18\x01 \x01(\v2\x16.google.protobuf.ValueH\x00R\x05value\x12\x1a\n" +
	"\aunknown\x18\x02 \x01(\bH\x00R\aunknown\x12\x1e\n" +
	"\tsensitive\x18\x03 \x01(\bH\x00R\tsensitive\x12 \n" +
	"\n" +
	"unresolved\x18\x04 \x01(\bH\x00R\n" +
	"unresolvedB\x06\n" +
	"\x04kind2Z\n" +
	"\vPlanService\x12K\n" +
	"\x04Plan\x12 .upjet.diff.v1alpha1.PlanRequest\x1a!.upjet.diff.v1alpha1.PlanResponseB4Z2github.com/crossplane/upjet/v2/proto/diff/v1alpha1b\x06proto3"

var (
	file_diff_v1alpha1_diff_proto_rawDescOnce sync.Once
	file_diff_v1alpha1_diff_proto_rawDescData []byte
)

func file_diff_v1alpha1_diff_proto_rawDescGZIP() []byte {
	file_diff_v1alpha1_diff_proto_rawDescOnce.Do(func() {
		file_diff_v1alpha1_diff_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_diff_v1alpha1_diff_proto_rawDesc), len(file_diff_v1alpha1_diff_proto_rawDesc)))
	})
	return file_diff_v1alpha1_diff_proto_rawDescData
}

var file_diff_v1alpha1_diff_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_diff_v1alpha1_diff_proto_goTypes = []any{
	(*PlanRequest)(nil),           // 0: upjet.diff.v1alpha1.PlanRequest
	(*PlanResponse)(nil),          // 1: upjet.diff.v1alpha1.PlanResponse
	(*FieldChange)(nil),           // 2: upjet.diff.v1alpha1.FieldChange
	(*FieldValue)(nil),            // 3: upjet.diff.v1alpha1.FieldValue
	(*structpb.Struct)(nil),       // 4: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*structpb.Value)(nil),        // 6: google.protobuf.Value
}
var file_diff_v1alpha1_diff_proto_depIdxs = []int32{
	4, // 0: upjet.diff.v1alpha1.PlanRequest.desired_resource:type_name -> google.protobuf.Struct
	4, // 1: upjet.diff.v1alpha1.PlanRequest.live_resource:type_name -> google.protobuf.Struct
	4, // 2: upjet.diff.v1alpha1.PlanRequest.kubernetes_object_store:type_name -> google.protobuf.Struct
	2, // 3: upjet.diff.v1alpha1.PlanResponse.changes:type_name -> upjet.diff.v1alpha1.FieldChange
	5, // 4: upjet.diff.v1alpha1.PlanResponse.computed_at:type_name -> google.protobuf.Timestamp
	3, // 5: upjet.diff.v1alpha1.FieldChange.current:type_name -> upjet.diff.v1alpha1.FieldValue
	3, // 6: upjet.diff.v1alpha1.FieldChange.desired:type_name -> upjet.diff.v1alpha1.FieldValue
	6, // 7: upjet.diff.v1alpha1.FieldValue.value:type_name -> google.protobuf.Value
	0, // 8: upjet.diff.v1alpha1.PlanService.Plan:input_type -> upjet.diff.v1alpha1.PlanRequest
	1, // 9: upjet.diff.v1alpha1.PlanService.Plan:output_type -> upjet.diff.v1alpha1.PlanResponse
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_diff_v1alpha1_diff_proto_init() }
func file_diff_v1alpha1_diff_proto_init() {
	if File_diff_v1alpha1_diff_proto != nil {
		return
	}
	file_diff_v1alpha1_diff_proto_msgTypes[3].OneofWrappers = []any{
		(*FieldValue_Value)(nil),
		(*FieldValue_Unknown)(nil),
		(*FieldValue_Sensitive)(nil),
		(*FieldValue_Unresolved)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_diff_v1alpha1_diff_proto_rawDesc), len(file_diff_v1alpha1_diff_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_diff_v1alpha1_diff_proto_goTypes,
		DependencyIndexes: file_diff_v1alpha1_diff_proto_depIdxs,
		MessageInfos:      file_diff_v1alpha1_diff_proto_msgTypes,
	}.Build()
	File_diff_v1alpha1_diff_proto = out.File
	file_diff_v1alpha1_diff_proto_goTypes = nil
	file_diff_v1alpha1_diff_proto_depIdxs = nil
}
